### ISSUE TITLE
Could you please provide the file of preprocessing.zip

### ISSUE THREAD

**Issue by lxcz1** [ericashimomoto/parameter-efficient-tvg#1]
The URL in the file download.sh cannot download the file properly. I can't access anything in there. Could you please provide the file of preprocessing.zip ?

**Comment by ericashimomoto** [comment]
Hi! Thanks for pointing out this file issue. Please, find the file in following link: https://drive.google.com/file/d/1exfeojXRnK9eeJjtcBYrBvL5Px3U29zU/view?usp=sharing

**Comment by lxcz1** [comment]
hello！Thank you very much for your documentation. I just remembered that because the website where you need to download files is down, all the files in it are not available. I'm so sorry that could you please send a copy of the complete file that needs to be downloaded in download.sh? Thank you very much.




七米工资
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ericashimomoto/parameter-efficient-tvg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月4日(星期六) 晚上10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ericashimomoto/parameter-efficient-tvg] Could you please provide the file of preprocessing.zip (Issue #1)





 
Hi! Thanks for pointing out this file issue. Please, find the file in following link: https://drive.google.com/file/d/1exfeojXRnK9eeJjtcBYrBvL5Px3U29zU/view?usp=sharing

**Comment by shuoyang129** [comment]
could you update all the other download links in the ./download.sh?  many thanks.
